version: "3"
services:
  react:                 
    container_name: react
    image: "darack/react:0.1"
    build:
      dockerfile: Dockerfile
      context: ./frontend   
    networks:
      - backend           
  express:           
    container_name: express
    image: "darack/express:0.1"               
    build:
      dockerfile: Dockerfile
      context: ./backend
    networks:
      - backend  
  nginx:
    restart: always
    container_name: "nginx"
    image: "darack/nginx:0.1"
    build:
      dockerfile: Dockerfile
      context: ./nginx
    networks:
      - backend
    ports: 
      - "80:80"
  redis:
    container_name: redis
    image: "darack/redis:0.1"
    build:
      dockerfile: Dockerfile
      context: ./redis
    volumes:
      - /home/darack/infrastudy/source/redis/data:/data
    networks:
      - backend


networks: 
  backend:
    driver: bridge
